#! /bin/bash -f
#
# Scriptfile
#
# rho    = density
# lmax   = number of steps
# nequil = number of equilibration steps
# dr     = maximum displacement
# npart  = number of particles

for rho in 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.85 1.9;
do

cat > input  <<endofdata
ibeg  nequil   lmax  nsamp
   0  10000    10000      1
    dr
  0.09
ndispl
    50
 npart    temp    rho
   100     2.0  ${rho}
 epsilon sigma  mass  cutoff
 1.0     1.0    1.0   3.5
endofdata
time  ../Source/mc_nvt>out_$rho
rm input
done
exit
